defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: slurm
- graph: multi_scale
- model: graphtransformer
- training: default
- override hydra/hydra_logging: disabled  
- override hydra/job_logging: disabled 
- _self_
- override diagnostics/plot: none


hydra:  
  output_subdir: null  
  run:  
    dir: .

data:
  resolution: o96
  forcing:
  - "cos_latitude"
  - "cos_longitude"
  - "sin_latitude"
  - "sin_longitude"
  - "cos_julian_day"
  - "cos_local_time"
  - "sin_julian_day"
  - "sin_local_time"
  - "insolation"
  - "lsm"
  - "z"

  diagnostic:
  - tp

  normalizer:
    max: 
    - "z"

dataloader:
  dataset: ${hardware.paths.data}/ERA5/${hardware.files.dataset}

  num_workers:
    training: 2
    validation: 2
    test: 2
    predict: 2

  limit_batches:
    training: null
    validation: null
    test: null
    predict: null

  batch_size:
    training: 1
    validation: 1
    test: 1
    predict: 1

  training:
    start: 1979-01-01
    end: 2021-12-31
    drop: ['sdor', 'slor', 'cp', 'u_600', 'v_600', 'z_600', 't_600', 'q_600', 'w_600']
    reorder: ${reorder} # this is needed to transfer learning, order of vars have to be the same
    statistics: ${hardware.paths.data}/ERA5/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr

  validation:
    start: 2022-01-01
    end: 2022-12-31
    drop: ['sdor', 'slor', 'cp', 'u_600', 'v_600', 'z_600', 't_600', 'q_600', 'w_600']
    reorder: ${reorder}
    statistics: ${hardware.paths.data}/ERA5/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr
  test:
    start: 2022-01-01
    end: 2022-12-31
    drop: ['sdor', 'slor', 'cp', 'u_600', 'v_600', 'z_600', 't_600', 'q_600', 'w_600']
    reorder: ${reorder}
    statistics: ${hardware.paths.data}/ERA5/aifs-od-an-oper-0001-mars-n320-2019-2023-6h-v6.zarr

diagnostics:
  log:
    mlflow:
      enabled: True
      authentication: True
      tracking_uri: https://mlflow.ecmwf.int
      experiment_name: 'metno'
      run_name: null #Change this
 
hardware:
  paths:
    data: /pfs/lustrep4/scratch/project_465002266/aifs/dataset/
    output: #Change this
    graph: /pfs/lustrep4/scratch/project_465002266/aifs/graphs/
  files:
    dataset: aifs-ea-an-oper-0001-mars-o96-1979-2022-6h-v6.zarr
    graph: o96_5p_12knn.pt
  num_gpus_per_model: 1

graph:
  overwrite: False
  
  edges:
  - source_name: ${graph.data}
    target_name: ${graph.hidden}
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges # options: KNNEdges, CutOffEdges
      num_nearest_neighbours: 12 # only for cutoff method
    attributes: ${graph.attributes.edges}
  - source_name: ${graph.hidden}
    # Processor configuration
    target_name: ${graph.hidden}
    edge_builders:
    - _target_: anemoi.graphs.edges.MultiScaleEdges
      x_hops: 1
    attributes: ${graph.attributes.edges}
  - source_name: ${graph.hidden}
    # Decoder configuration
    target_name: ${graph.data}
    edge_builders:
    - _target_: anemoi.graphs.edges.KNNEdges # options: KNNEdges, CutOffEdges
      num_nearest_neighbours: 3 # only for knn method
    attributes: ${graph.attributes.edges}

  attributes:
    edges:
      edge_length:
        _target_: anemoi.graphs.edges.attributes.EdgeLength
        norm: unit-max

model:
  num_channels: 1024
  trainable_parameters:
    data: 0
    hidden: 0
    data2hidden: 0
    hidden2data: 0
    hidden2hidden: 0

training:
  max_epochs: null
  max_steps: 150000
  lr:
    rate: 6.25e-5
    min: 3e-7

reorder: ['10u',
 '10v',
 '2d',
 '2t',
 'cos_julian_day',
 'cos_latitude',
 'cos_local_time',
 'cos_longitude',
 'insolation',
 'lsm',
 'msl',
 'q_100',
 'q_1000',
 'q_150',
 'q_200',
 'q_250',
 'q_300',
 'q_400',
 'q_50',
 'q_500',
 'q_700',
 'q_850',
 'q_925',
 'sin_julian_day',
 'sin_latitude',
 'sin_local_time',
 'sin_longitude',
 'skt',
 'sp',
 't_100',
 't_1000',
 't_150',
 't_200',
 't_250',
 't_300',
 't_400',
 't_50',
 't_500',
 't_700',
 't_850',
 't_925',
 'tcw',
 'tp',
 'u_100',
 'u_1000',
 'u_150',
 'u_200',
 'u_250',
 'u_300',
 'u_400',
 'u_50',
 'u_500',
 'u_700',
 'u_850',
 'u_925',
 'v_100',
 'v_1000',
 'v_150',
 'v_200',
 'v_250',
 'v_300',
 'v_400',
 'v_50',
 'v_500',
 'v_700',
 'v_850',
 'v_925',
 'w_100',
 'w_1000',
 'w_150',
 'w_200',
 'w_250',
 'w_300',
 'w_400',
 'w_50',
 'w_500',
 'w_700',
 'w_850',
 'w_925',
 'z',
 'z_100',
 'z_1000',
 'z_150',
 'z_200',
 'z_250',
 'z_300',
 'z_400',
 'z_50',
 'z_500',
 'z_700',
 'z_850',
 'z_925']



